using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace AutoDispatch;

[Generator]
public sealed class AutoDispatchGenerator : IIncrementalGenerator
{
    private const string AttributeSource = @"// <auto-generated by AutoDispatch.Generator/>
#nullable enable
using System;

namespace AutoDispatch
{
    /// <summary>Controls the DI lifetime used when registering a handler via AddAutoDispatch().</summary>
    public enum HandlerLifetime
    {
        /// <summary>Register as a scoped service (default).</summary>
        Scoped = 0,
        /// <summary>Register as a singleton service.</summary>
        Singleton = 1,
        /// <summary>Register as a transient service.</summary>
        Transient = 2
    }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class HandlerAttribute : Attribute
    {
        /// <summary>The DI lifetime for this handler. Defaults to Scoped.</summary>
        public HandlerLifetime Lifetime { get; set; } = HandlerLifetime.Scoped;
    }

    /// <summary>
    /// Semantic alias for <see cref=""HandlerAttribute""/> — use on command handlers to make
    /// intent explicit. Behaves identically to <c>[Handler]</c>.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class CommandHandlerAttribute : Attribute
    {
        /// <summary>The DI lifetime for this handler. Defaults to Scoped.</summary>
        public HandlerLifetime Lifetime { get; set; } = HandlerLifetime.Scoped;
    }

    /// <summary>
    /// Semantic alias for <see cref=""HandlerAttribute""/> — use on query handlers to make
    /// intent explicit. Behaves identically to <c>[Handler]</c>.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class QueryHandlerAttribute : Attribute
    {
        /// <summary>The DI lifetime for this handler. Defaults to Scoped.</summary>
        public HandlerLifetime Lifetime { get; set; } = HandlerLifetime.Scoped;
    }

    public readonly struct Unit { public static readonly Unit Value = default; }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class BehaviorAttribute : Attribute
    {
        public int Order { get; set; } = 0;
    }

    /// <summary>
    /// Marks a class as a notification handler. Unlike <see cref=""HandlerAttribute""/>, many
    /// <see cref=""NotificationHandlerAttribute""/> classes may handle the same notification type —
    /// AutoDispatch fans a single <c>PublishAsync</c> call out to every registered handler.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class NotificationHandlerAttribute : Attribute
    {
        /// <summary>The DI lifetime for this handler. Defaults to Scoped.</summary>
        public HandlerLifetime Lifetime { get; set; } = HandlerLifetime.Scoped;
    }

    public interface IPipelineBehavior<TCommand, TResult>
    {
        System.Threading.Tasks.Task<TResult> HandleAsync(
            TCommand command,
            System.Func<System.Threading.Tasks.Task<TResult>> next,
            System.Threading.CancellationToken ct = default);
    }
}
";

    private static readonly DiagnosticDescriptor AD001 = new(
        id: "AD001",
        title: "Handler has no dispatch methods",
        messageFormat: "[Handler] on '{0}' has no `Handle` or `HandleAsync` methods. No dispatch methods will be generated.",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AD002 = new(
        id: "AD002",
        title: "Duplicate handler for command",
        messageFormat: "Duplicate handler for command '{0}': both '{1}' and '{2}' define a `Handle`/`HandleAsync` method for this command type. Remove one handler or rename the method.",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AD003 = new(
        id: "AD003",
        title: "HandleAsync missing CancellationToken",
        messageFormat: "`HandleAsync` on '{0}' for command '{1}' is missing a `CancellationToken` parameter. Consider adding `CancellationToken ct = default` as the second parameter.",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AD004 = new(
        id: "AD004",
        title: "Behavior must be an open generic class",
        messageFormat: "[Behavior] on '{0}' must be a public, non-abstract class with exactly two type parameters so AutoDispatch can close it as `<TCommand, TResult>`",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AD005 = new(
        id: "AD005",
        title: "Behavior must implement IPipelineBehavior",
        messageFormat: "[Behavior] on '{0}' must implement `AutoDispatch.IPipelineBehavior<TCommand, TResult>` using its declared type parameters",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AD006 = new(
        id: "AD006",
        title: "Behavior has an invalid HandleAsync signature",
        messageFormat: "[Behavior] on '{0}' must declare `public Task<TResult> HandleAsync(TCommand command, Func<Task<TResult>> next, CancellationToken ct = default)`",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AD007 = new(
        id: "AD007",
        title: "Notification handler has no dispatch method",
        messageFormat: "[NotificationHandler] on '{0}' has no `HandleAsync(TNotification, CancellationToken)` method. No publish dispatch will be generated for this handler.",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AD008 = new(
        id: "AD008",
        title: "Notification HandleAsync missing CancellationToken",
        messageFormat: "`HandleAsync` on '{0}' for notification '{1}' is missing a `CancellationToken` parameter. Consider adding `CancellationToken ct = default` as the second parameter.",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly SymbolDisplayFormat FullyQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("AutoDispatch.Attributes.g.cs", AttributeSource));

        var handlers = MakeHandlerProvider(context, "AutoDispatch.HandlerAttribute")
            .Collect()
            .Combine(MakeHandlerProvider(context, "AutoDispatch.CommandHandlerAttribute").Collect())
            .Combine(MakeHandlerProvider(context, "AutoDispatch.QueryHandlerAttribute").Collect());

        var behaviors = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoDispatch.BehaviorAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => TransformBehavior(ctx, ct))
            .Where(static b => b is not null)
            .Select(static (b, _) => b!)
            .Collect();

        var notificationHandlers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoDispatch.NotificationHandlerAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => TransformNotificationHandler(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!)
            .Collect();

        var allInputs = handlers.Combine(behaviors).Combine(notificationHandlers);

        context.RegisterSourceOutput(allInputs, static (ctx, tuple) =>
        {
            var ((handlersTuple, behaviorList), notificationList) = tuple;
            var ((h1, h2), h3) = handlersTuple;
            Generate(ctx, h1.AddRange(h2).AddRange(h3), behaviorList, notificationList);
        });
    }

    private static IncrementalValuesProvider<HandlerInfo> MakeHandlerProvider(
        IncrementalGeneratorInitializationContext context,
        string attributeFqn) =>
        context.SyntaxProvider
            .ForAttributeWithMetadataName(
                attributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => TransformHandler(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

    private static HandlerInfo? TransformHandler(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        var info = new HandlerInfo
        {
            HandlerTypeFqn = ToFullyQualified(typeSymbol),
            HandlerDisplayName = typeSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            Location = typeSymbol.Locations.FirstOrDefault() ?? Location.None,
            LifetimeMethod = ReadLifetimeMethod(context.Attributes)
        };

        var cancellationTokenType = context.SemanticModel.Compilation.GetTypeByMetadataName("System.Threading.CancellationToken");

        foreach (var member in typeSymbol.GetMembers().OfType<IMethodSymbol>())
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (member.MethodKind != MethodKind.Ordinary ||
                member.IsStatic ||
                member.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            if (member.Name == "Handle")
            {
                TryAddSyncMethod(info, member);
                continue;
            }

            if (member.Name == "HandleAsync")
            {
                TryAddAsyncMethod(info, member, cancellationTokenType);
            }
        }

        return info;
    }

    private static NotificationHandlerInfo? TransformNotificationHandler(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        var info = new NotificationHandlerInfo
        {
            HandlerTypeFqn = ToFullyQualified(typeSymbol),
            HandlerDisplayName = typeSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            Location = typeSymbol.Locations.FirstOrDefault() ?? Location.None,
            LifetimeMethod = ReadLifetimeMethod(context.Attributes)
        };

        var cancellationTokenType = context.SemanticModel.Compilation.GetTypeByMetadataName("System.Threading.CancellationToken");

        foreach (var member in typeSymbol.GetMembers("HandleAsync").OfType<IMethodSymbol>())
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (member.MethodKind != MethodKind.Ordinary ||
                member.IsStatic ||
                member.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            TryAddNotificationMethod(info, member, cancellationTokenType);
        }

        return info;
    }

    private static void TryAddNotificationMethod(
        NotificationHandlerInfo handler,
        IMethodSymbol method,
        INamedTypeSymbol? cancellationTokenType)
    {
        if (method.Parameters.Length is < 1 or > 2)
        {
            return;
        }

        // Notification handlers return Task only — they publish, they don't produce a result.
        if (method.ReturnType.ToDisplayString() != "System.Threading.Tasks.Task")
        {
            return;
        }

        if (method.Parameters.Length == 2 &&
            (cancellationTokenType is null ||
             !SymbolEqualityComparer.Default.Equals(method.Parameters[1].Type, cancellationTokenType)))
        {
            return;
        }

        handler.Methods.Add(new NotificationMethodInfo
        {
            NotificationTypeFqn = ToFullyQualified(method.Parameters[0].Type),
            NotificationDisplayName = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            HandlerTypeFqn = handler.HandlerTypeFqn,
            HandlerDisplayName = handler.HandlerDisplayName,
            HasCancellationTokenParameter = method.Parameters.Length == 2,
            Location = method.Locations.FirstOrDefault() ?? handler.Location,
            DocCommentXml = GetDocCommentXml(method)
        });
    }

    private static void TryAddSyncMethod(HandlerInfo handler, IMethodSymbol method)
    {
        if (method.Parameters.Length != 1 || IsTaskLike(method.ReturnType))
        {
            return;
        }

        handler.Methods.Add(new DispatchMethodInfo
        {
            CommandTypeFqn = ToFullyQualified(method.Parameters[0].Type),
            CommandDisplayName = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            HandlerTypeFqn = handler.HandlerTypeFqn,
            HandlerDisplayName = handler.HandlerDisplayName,
            ReturnTypeFqn = method.ReturnsVoid ? "void" : ToFullyQualified(method.ReturnType),
            MethodName = "Handle",
            IsAsync = false,
            HasCancellationTokenParameter = false,
            Location = method.Locations.FirstOrDefault() ?? handler.Location,
            DocCommentXml = GetDocCommentXml(method)
        });
    }

    private static void TryAddAsyncMethod(
        HandlerInfo handler,
        IMethodSymbol method,
        INamedTypeSymbol? cancellationTokenType)
    {
        if (method.Parameters.Length is < 1 or > 2)
        {
            return;
        }

        if (!IsTaskLike(method.ReturnType))
        {
            return;
        }

        if (method.Parameters.Length == 2 &&
            (cancellationTokenType is null ||
             !SymbolEqualityComparer.Default.Equals(method.Parameters[1].Type, cancellationTokenType)))
        {
            return;
        }

        handler.Methods.Add(new DispatchMethodInfo
        {
            CommandTypeFqn = ToFullyQualified(method.Parameters[0].Type),
            CommandDisplayName = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            HandlerTypeFqn = handler.HandlerTypeFqn,
            HandlerDisplayName = handler.HandlerDisplayName,
            ReturnTypeFqn = ToFullyQualified(method.ReturnType),
            MethodName = "HandleAsync",
            IsAsync = true,
            HasCancellationTokenParameter = method.Parameters.Length == 2,
            AsyncResultTypeFqn = GetAsyncResultTypeFqn(method.ReturnType),
            Location = method.Locations.FirstOrDefault() ?? handler.Location,
            DocCommentXml = GetDocCommentXml(method)
        });
    }

    /// <summary>
    /// Reads the handler method's own XML doc comment (if any) so it can be forwarded onto
    /// the generated <c>IDispatcher</c> member, giving callers real IntelliSense instead of
    /// undocumented generated code.
    /// </summary>
    private static string? GetDocCommentXml(IMethodSymbol method)
    {
        var xml = method.GetDocumentationCommentXml(expandIncludes: true);
        return string.IsNullOrWhiteSpace(xml) ? null : xml;
    }

    /// <summary>
    /// Converts a symbol's raw `GetDocumentationCommentXml()` output (a single
    /// &lt;member&gt;...&lt;/member&gt; fragment) into indented `///` doc-comment lines
    /// suitable for emission above a generated member.
    /// </summary>
    private static void AppendDocComment(StringBuilder sb, string? docCommentXml, string indent)
    {
        if (string.IsNullOrWhiteSpace(docCommentXml))
        {
            return;
        }

        System.Xml.Linq.XElement member;
        try
        {
            member = System.Xml.Linq.XElement.Parse(docCommentXml);
        }
        catch (System.Xml.XmlException)
        {
            return;
        }

        foreach (var node in member.Nodes())
        {
            var text = node.ToString(System.Xml.Linq.SaveOptions.DisableFormatting);
            foreach (var line in text.Split('\n'))
            {
                var trimmed = line.TrimEnd('\r').Trim();
                if (trimmed.Length == 0)
                {
                    continue;
                }

                sb.Append(indent);
                sb.Append("/// ");
                sb.AppendLine(trimmed);
            }
        }
    }

    private static void Generate(
        SourceProductionContext context,
        ImmutableArray<HandlerInfo> handlers,
        ImmutableArray<BehaviorCandidate> behaviorCandidates,
        ImmutableArray<NotificationHandlerInfo> notificationHandlers)
    {
        var behaviors = new List<BehaviorInfo>();
        var seenBehaviorTypes = new HashSet<string>(StringComparer.Ordinal);
        foreach (var candidate in behaviorCandidates)
        {
            foreach (var diagnostic in candidate.Diagnostics)
            {
                context.ReportDiagnostic(diagnostic);
            }

            if (candidate.Behavior is null || !seenBehaviorTypes.Add(candidate.Behavior.UnboundTypeFqn))
            {
                continue;
            }

            behaviors.Add(candidate.Behavior);
        }

        var registrations = new Dictionary<string, string>(StringComparer.Ordinal); // fqn → lifetime method
        var dispatchMethods = Array.Empty<DispatchMethodInfo>();

        if (!handlers.IsDefaultOrEmpty)
        {
            var methods = new List<DispatchMethodInfo>();

            foreach (var handler in handlers)
            {
                registrations[handler.HandlerTypeFqn] = handler.LifetimeMethod;

                if (handler.Methods.Count == 0)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        AD001,
                        handler.Location,
                        handler.HandlerDisplayName));
                    continue;
                }

                foreach (var method in handler.Methods)
                {
                    methods.Add(method);

                    if (method.IsAsync && !method.HasCancellationTokenParameter)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            AD003,
                            method.Location,
                            method.HandlerDisplayName,
                            method.CommandDisplayName));
                    }
                }
            }

            var duplicateCommands = new HashSet<string>(StringComparer.Ordinal);
            foreach (var group in methods.GroupBy(static method => method.CommandTypeFqn, StringComparer.Ordinal))
            {
                if (group.Count() <= 1)
                {
                    continue;
                }

                duplicateCommands.Add(group.Key);
                var ordered = group
                    .OrderBy(static method => method.HandlerTypeFqn, StringComparer.Ordinal)
                    .ThenBy(static method => method.MethodName, StringComparer.Ordinal)
                    .ToArray();

                var first = ordered[0];
                for (var i = 1; i < ordered.Length; i++)
                {
                    var duplicate = ordered[i];
                    context.ReportDiagnostic(Diagnostic.Create(
                        AD002,
                        duplicate.Location,
                        duplicate.CommandDisplayName,
                        first.HandlerDisplayName,
                        duplicate.HandlerDisplayName));
                }
            }

            dispatchMethods = methods
                .Where(method => !duplicateCommands.Contains(method.CommandTypeFqn))
                .OrderBy(static method => method.CommandTypeFqn, StringComparer.Ordinal)
                .ThenBy(static method => method.HandlerTypeFqn, StringComparer.Ordinal)
                .ToArray();
        }

        var notificationGroups = Array.Empty<NotificationGroup>();

        if (!notificationHandlers.IsDefaultOrEmpty)
        {
            var notificationMethods = new List<NotificationMethodInfo>();

            foreach (var handler in notificationHandlers)
            {
                registrations[handler.HandlerTypeFqn] = handler.LifetimeMethod;

                if (handler.Methods.Count == 0)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        AD007,
                        handler.Location,
                        handler.HandlerDisplayName));
                    continue;
                }

                foreach (var method in handler.Methods)
                {
                    notificationMethods.Add(method);

                    if (!method.HasCancellationTokenParameter)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            AD008,
                            method.Location,
                            method.HandlerDisplayName,
                            method.NotificationDisplayName));
                    }
                }
            }

            // Unlike commands, many handlers may legitimately subscribe to the same notification
            // type — every one of them fires when PublishAsync is called, so there is no
            // "duplicate handler" diagnostic here.
            notificationGroups = notificationMethods
                .GroupBy(static method => method.NotificationTypeFqn, StringComparer.Ordinal)
                .Select(static group => new NotificationGroup(
                    group.Key,
                    group.OrderBy(static method => method.HandlerTypeFqn, StringComparer.Ordinal).ToArray()))
                .OrderBy(static group => group.NotificationTypeFqn, StringComparer.Ordinal)
                .ToArray();
        }

        if (dispatchMethods.Length == 0 && notificationGroups.Length == 0)
        {
            return;
        }

        context.AddSource("AutoDispatch.Dispatcher.g.cs", GenerateDispatcherSource(dispatchMethods, behaviors, notificationGroups));
        context.AddSource("AutoDispatch.Registration.g.cs", GenerateRegistrationSource(registrations, behaviors));
    }

    private static string GenerateDispatcherSource(IReadOnlyList<DispatchMethodInfo> methods, IReadOnlyList<BehaviorInfo> behaviors, IReadOnlyList<NotificationGroup> notificationGroups)
    {
        var sortedBehaviors = behaviors
            .OrderBy(static b => b.Order)
            .ThenBy(static b => b.SortFilePath, StringComparer.Ordinal)
            .ThenBy(static b => b.SortSpanStart)
            .ThenBy(static b => b.UnboundTypeFqn, StringComparer.Ordinal)
            .ToArray();
        var hasBehaviors = sortedBehaviors.Length > 0;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoDispatch.Generator/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoDispatch");
        sb.AppendLine("{");
        sb.AppendLine("    public interface IDispatcher");
        sb.AppendLine("    {");

        foreach (var method in methods)
        {
            AppendDocComment(sb, method.DocCommentXml, "        ");

            sb.Append("        ");
            sb.Append(GetInterfaceReturnType(method));
            sb.Append(' ');
            sb.Append(GetDispatchMethodName(method));
            sb.Append('(');
            sb.Append(method.CommandTypeFqn);
            sb.Append(" command");
            if (method.IsAsync)
            {
                sb.Append(", global::System.Threading.CancellationToken ct = default");
            }

            sb.AppendLine(");");
        }

        foreach (var group in notificationGroups)
        {
            sb.Append("        global::System.Threading.Tasks.Task PublishAsync(");
            sb.Append(group.NotificationTypeFqn);
            sb.AppendLine(" notification, global::System.Threading.CancellationToken ct = default);");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal sealed class Dispatcher : IDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.IServiceProvider _sp;");
        sb.AppendLine();
        sb.AppendLine("        public Dispatcher(global::System.IServiceProvider sp) => _sp = sp;");
        sb.AppendLine();

        foreach (var method in methods)
        {
            if (!method.IsAsync || !hasBehaviors)
            {
                // Simple expression-body form (sync or async with no behaviors)
                AppendDocComment(sb, method.DocCommentXml, "        ");
                sb.Append("        public ");
                sb.Append(GetInterfaceReturnType(method));
                sb.Append(' ');
                sb.Append(GetDispatchMethodName(method));
                sb.Append('(');
                sb.Append(method.CommandTypeFqn);
                sb.Append(" command");
                if (method.IsAsync)
                {
                    sb.Append(", global::System.Threading.CancellationToken ct = default");
                }

                sb.AppendLine(")");
                sb.Append("            => this._sp.GetRequiredService<");
                sb.Append(method.HandlerTypeFqn);
                sb.Append(">().");
                sb.Append(method.MethodName);
                sb.Append("(command");
                if (method.IsAsync && method.HasCancellationTokenParameter)
                {
                    sb.Append(", ct");
                }

                sb.AppendLine(");");
                sb.AppendLine();
            }
            else
            {
                // Async with pipeline
                var resultFqn = method.AsyncResultTypeFqn ?? "global::AutoDispatch.Unit";
                var pipelineType = $"global::System.Func<global::System.Threading.Tasks.Task<{resultFqn}>>";

                AppendDocComment(sb, method.DocCommentXml, "        ");

                // Pipeline execution order, outermost-first, to make the generated chain easy to reason about.
                var handlerShortName = GetShortTypeName(method.HandlerTypeFqn);
                var pipelineOrder = string.Join(" -> ", sortedBehaviors.Select(static b => GetShortTypeName(b.UnboundTypeFqn)));
                sb.AppendLine($"        // Pipeline: {pipelineOrder} -> {handlerShortName}.{method.MethodName} -> {pipelineOrder}");
                sb.AppendLine($"        public {GetInterfaceReturnType(method)} {GetDispatchMethodName(method)}({method.CommandTypeFqn} command, global::System.Threading.CancellationToken ct = default)");
                sb.AppendLine("        {");

                if (method.AsyncResultTypeFqn != null)
                {
                    sb.AppendLine($"            {pipelineType} pipeline = () => this._sp.GetRequiredService<{method.HandlerTypeFqn}>().{method.MethodName}(command{(method.HasCancellationTokenParameter ? ", ct" : "")});");
                }
                else
                {
                    sb.AppendLine($"            {pipelineType} pipeline = async () => {{ await this._sp.GetRequiredService<{method.HandlerTypeFqn}>().{method.MethodName}(command{(method.HasCancellationTokenParameter ? ", ct" : "")}); return global::AutoDispatch.Unit.Value; }};");
                }

                for (var i = sortedBehaviors.Length - 1; i >= 0; i--)
                {
                    var b = sortedBehaviors[i];
                    var behaviorTypeFqn = b.UnboundTypeFqn.Replace("<,>", $"<{method.CommandTypeFqn}, {resultFqn}>");
                    sb.AppendLine($"            var _b{i} = this._sp.GetRequiredService<{behaviorTypeFqn}>();");
                    sb.AppendLine($"            var _p{i} = pipeline;");
                    sb.AppendLine($"            pipeline = () => _b{i}.HandleAsync(command, _p{i}, ct);");
                }

                sb.AppendLine("            return pipeline();");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
        }

        foreach (var group in notificationGroups)
        {
            // Fan-out publish: every registered handler for this notification type runs in
            // deterministic (handler-type-name) order. A handler throwing stops the remaining
            // handlers from running, matching MediatR's default ForeachAwaitPublisher behavior.
            var handlerNames = string.Join(", ", group.Methods.Select(static m => GetShortTypeName(m.HandlerTypeFqn)));
            sb.AppendLine($"        // Publish fan-out: {handlerNames}");
            sb.AppendLine($"        public async global::System.Threading.Tasks.Task PublishAsync({group.NotificationTypeFqn} notification, global::System.Threading.CancellationToken ct = default)");
            sb.AppendLine("        {");

            foreach (var method in group.Methods)
            {
                sb.Append("            await this._sp.GetRequiredService<");
                sb.Append(method.HandlerTypeFqn);
                sb.Append(">().HandleAsync(notification");
                if (method.HasCancellationTokenParameter)
                {
                    sb.Append(", ct");
                }

                sb.AppendLine(").ConfigureAwait(false);");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateRegistrationSource(Dictionary<string, string> registrations, IReadOnlyList<BehaviorInfo> behaviors)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoDispatch.Generator/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoDispatch");
        sb.AppendLine("{");
        sb.AppendLine("    public static class AutoDispatchServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoDispatch(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var kvp in registrations.OrderBy(k => k.Key, StringComparer.Ordinal))
        {
            sb.Append("            services.");
            sb.Append(kvp.Value);
            sb.Append('<');
            sb.Append(kvp.Key);
            sb.AppendLine(">();");
        }

        foreach (var behavior in behaviors.OrderBy(static b => b.UnboundTypeFqn, StringComparer.Ordinal))
        {
            sb.AppendLine($"            services.AddScoped(typeof({behavior.UnboundTypeFqn}));");
        }

        sb.AppendLine("            services.AddScoped<global::AutoDispatch.IDispatcher, global::AutoDispatch.Dispatcher>();");
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ReadLifetimeMethod(ImmutableArray<AttributeData> attributes)
    {
        foreach (var attr in attributes)
        {
            foreach (var arg in attr.NamedArguments)
            {
                if (arg.Key == "Lifetime" && arg.Value.Value is int val)
                {
                    return val switch
                    {
                        1 => "AddSingleton",
                        2 => "AddTransient",
                        _ => "AddScoped"
                    };
                }
            }
        }
        return "AddScoped";
    }

    private static bool IsTaskLike(ITypeSymbol returnType)
    {
        if (returnType is not INamedTypeSymbol namedType)
        {
            return false;
        }

        var constructedFrom = namedType.ConstructedFrom.ToDisplayString();
        return namedType.ToDisplayString() == "System.Threading.Tasks.Task" ||
               constructedFrom == "System.Threading.Tasks.Task<TResult>";
    }

    private static string ToFullyQualified(ITypeSymbol typeSymbol) =>
        typeSymbol.ToDisplayString(FullyQualifiedFormat);

    private static string GetDispatchMethodName(DispatchMethodInfo method) =>
        method.IsAsync ? "SendAsync" : "Send";

    /// <summary>Strips "global::", namespace segments, and generic arity from a fully-qualified type name for readable pipeline comments.</summary>
    private static string GetShortTypeName(string fullyQualifiedName)
    {
        var name = fullyQualifiedName;
        if (name.StartsWith("global::", StringComparison.Ordinal))
        {
            name = name.Substring("global::".Length);
        }

        var genericIndex = name.IndexOf('<');
        if (genericIndex >= 0)
        {
            name = name.Substring(0, genericIndex);
        }

        var lastDot = name.LastIndexOf('.');
        return lastDot >= 0 ? name.Substring(lastDot + 1) : name;
    }

    private static string GetInterfaceReturnType(DispatchMethodInfo method) =>
        method.ReturnTypeFqn;

    private static string? GetAsyncResultTypeFqn(ITypeSymbol returnType)
    {
        if (returnType is INamedTypeSymbol { TypeArguments.Length: 1 } named)
        {
            return ToFullyQualified(named.TypeArguments[0]);
        }

        return null;
    }

    private static BehaviorCandidate? TransformBehavior(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        var behaviorDisplayName = typeSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
        var location = typeSymbol.Locations.FirstOrDefault() ?? Location.None;

        if (typeSymbol.TypeKind != TypeKind.Class ||
            typeSymbol.DeclaredAccessibility != Accessibility.Public ||
            typeSymbol.IsAbstract ||
            typeSymbol.TypeParameters.Length != 2)
        {
            return new BehaviorCandidate
            {
                Diagnostics = ImmutableArray.Create(Diagnostic.Create(
                    AD004,
                    location,
                    behaviorDisplayName))
            };
        }

        var pipelineBehaviorType = context.SemanticModel.Compilation.GetTypeByMetadataName("AutoDispatch.IPipelineBehavior`2");
        var typeParameters = typeSymbol.TypeParameters;
        var implementsPipelineBehavior =
            pipelineBehaviorType is not null &&
            typeSymbol.AllInterfaces.Any(interfaceSymbol =>
                SymbolEqualityComparer.Default.Equals(interfaceSymbol.OriginalDefinition, pipelineBehaviorType) &&
                interfaceSymbol.TypeArguments.Length == 2 &&
                SymbolEqualityComparer.Default.Equals(interfaceSymbol.TypeArguments[0], typeParameters[0]) &&
                SymbolEqualityComparer.Default.Equals(interfaceSymbol.TypeArguments[1], typeParameters[1]));

        if (!implementsPipelineBehavior)
        {
            return new BehaviorCandidate
            {
                Diagnostics = ImmutableArray.Create(Diagnostic.Create(
                    AD005,
                    location,
                    behaviorDisplayName))
            };
        }

        if (!HasValidBehaviorHandleAsync(typeSymbol, context.SemanticModel.Compilation))
        {
            return new BehaviorCandidate
            {
                Diagnostics = ImmutableArray.Create(Diagnostic.Create(
                    AD006,
                    location,
                    behaviorDisplayName))
            };
        }

        var order = 0;
        foreach (var attr in context.Attributes)
        {
            foreach (var arg in attr.NamedArguments)
            {
                if (arg.Key == "Order" && arg.Value.Value is int v)
                {
                    order = v;
                }
            }
        }

        return new BehaviorCandidate
        {
            Behavior = new BehaviorInfo
            {
                UnboundTypeFqn = ToFullyQualified(typeSymbol.ConstructUnboundGenericType()),
                Order = order,
                SortFilePath = typeSymbol.Locations.FirstOrDefault()?.SourceTree?.FilePath ?? string.Empty,
                SortSpanStart = typeSymbol.Locations.FirstOrDefault()?.SourceSpan.Start ?? 0,
                Location = location
            }
        };
    }

    private static bool HasValidBehaviorHandleAsync(INamedTypeSymbol typeSymbol, Compilation compilation)
    {
        var cancellationTokenType = compilation.GetTypeByMetadataName("System.Threading.CancellationToken");
        var taskType = compilation.GetTypeByMetadataName("System.Threading.Tasks.Task`1");
        var funcType = compilation.GetTypeByMetadataName("System.Func`1");

        if (cancellationTokenType is null || taskType is null || funcType is null)
        {
            return false;
        }

        foreach (var method in typeSymbol.GetMembers("HandleAsync").OfType<IMethodSymbol>())
        {
            if (method.MethodKind != MethodKind.Ordinary ||
                method.IsStatic ||
                method.DeclaredAccessibility != Accessibility.Public ||
                method.Parameters.Length != 3 ||
                !SymbolEqualityComparer.Default.Equals(method.Parameters[0].Type, typeSymbol.TypeParameters[0]) ||
                !SymbolEqualityComparer.Default.Equals(method.Parameters[2].Type, cancellationTokenType))
            {
                continue;
            }

            if (method.ReturnType is not INamedTypeSymbol returnType ||
                !SymbolEqualityComparer.Default.Equals(returnType.OriginalDefinition, taskType) ||
                returnType.TypeArguments.Length != 1 ||
                !SymbolEqualityComparer.Default.Equals(returnType.TypeArguments[0], typeSymbol.TypeParameters[1]))
            {
                continue;
            }

            if (method.Parameters[1].Type is not INamedTypeSymbol nextType ||
                !SymbolEqualityComparer.Default.Equals(nextType.OriginalDefinition, funcType) ||
                nextType.TypeArguments.Length != 1)
            {
                continue;
            }

            if (nextType.TypeArguments[0] is not INamedTypeSymbol nextResultType ||
                !SymbolEqualityComparer.Default.Equals(nextResultType.OriginalDefinition, taskType) ||
                nextResultType.TypeArguments.Length != 1 ||
                !SymbolEqualityComparer.Default.Equals(nextResultType.TypeArguments[0], typeSymbol.TypeParameters[1]))
            {
                continue;
            }

            return true;
        }

        return false;
    }

    private sealed class HandlerInfo
    {
        public string HandlerTypeFqn { get; set; } = string.Empty;

        public string HandlerDisplayName { get; set; } = string.Empty;

        public Location Location { get; set; } = Location.None;

        public string LifetimeMethod { get; set; } = "AddScoped";

        public List<DispatchMethodInfo> Methods { get; } = new();
    }

    private sealed class DispatchMethodInfo
    {
        public string CommandTypeFqn { get; set; } = string.Empty;

        public string CommandDisplayName { get; set; } = string.Empty;

        public string HandlerTypeFqn { get; set; } = string.Empty;

        public string HandlerDisplayName { get; set; } = string.Empty;

        public string ReturnTypeFqn { get; set; } = string.Empty;

        public string MethodName { get; set; } = string.Empty;

        public bool IsAsync { get; set; }

        public bool HasCancellationTokenParameter { get; set; }

        public string? AsyncResultTypeFqn { get; set; }

        public Location Location { get; set; } = Location.None;

        public string? DocCommentXml { get; set; }
    }

    private sealed class BehaviorInfo
    {
        public string UnboundTypeFqn { get; set; } = string.Empty;

        public int Order { get; set; }

        public string SortFilePath { get; set; } = string.Empty;

        public int SortSpanStart { get; set; }

        public Location Location { get; set; } = Location.None;
    }

    private sealed class BehaviorCandidate
    {
        public BehaviorInfo? Behavior { get; set; }

        public ImmutableArray<Diagnostic> Diagnostics { get; set; } = ImmutableArray<Diagnostic>.Empty;
    }

    private sealed class NotificationHandlerInfo
    {
        public string HandlerTypeFqn { get; set; } = string.Empty;

        public string HandlerDisplayName { get; set; } = string.Empty;

        public Location Location { get; set; } = Location.None;

        public string LifetimeMethod { get; set; } = "AddScoped";

        public List<NotificationMethodInfo> Methods { get; } = new();
    }

    private sealed class NotificationMethodInfo
    {
        public string NotificationTypeFqn { get; set; } = string.Empty;

        public string NotificationDisplayName { get; set; } = string.Empty;

        public string HandlerTypeFqn { get; set; } = string.Empty;

        public string HandlerDisplayName { get; set; } = string.Empty;

        public bool HasCancellationTokenParameter { get; set; }

        public Location Location { get; set; } = Location.None;

        public string? DocCommentXml { get; set; }
    }

    /// <summary>All the handlers subscribed to a single notification type, in the deterministic
    /// order AutoDispatch will invoke them from the generated `PublishAsync` method.</summary>
    private sealed class NotificationGroup
    {
        public NotificationGroup(string notificationTypeFqn, IReadOnlyList<NotificationMethodInfo> methods)
        {
            NotificationTypeFqn = notificationTypeFqn;
            Methods = methods;
        }

        public string NotificationTypeFqn { get; }

        public IReadOnlyList<NotificationMethodInfo> Methods { get; }
    }
}
