using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace AutoDispatch;

[Generator]
public sealed class AutoDispatchGenerator : IIncrementalGenerator
{
    private const string AttributeSource = @"// <auto-generated by AutoDispatch.Generator/>
#nullable enable
using System;

namespace AutoDispatch
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class HandlerAttribute : Attribute { }
}
";

    private static readonly DiagnosticDescriptor AD001 = new(
        id: "AD001",
        title: "Handler has no dispatch methods",
        messageFormat: "[Handler] on '{0}' has no `Handle` or `HandleAsync` methods. No dispatch methods will be generated.",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AD002 = new(
        id: "AD002",
        title: "Duplicate handler for command",
        messageFormat: "Duplicate handler for command '{0}': both '{1}' and '{2}' define a `Handle`/`HandleAsync` method for this command type. Remove one handler or rename the method.",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AD003 = new(
        id: "AD003",
        title: "HandleAsync missing CancellationToken",
        messageFormat: "`HandleAsync` on '{0}' for command '{1}' is missing a `CancellationToken` parameter. Consider adding `CancellationToken ct = default` as the second parameter.",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly SymbolDisplayFormat FullyQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("AutoDispatch.Attributes.g.cs", AttributeSource));

        var handlers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoDispatch.HandlerAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => TransformHandler(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(handlers.Collect(), static (ctx, handlers) => Generate(ctx, handlers));
    }

    private static HandlerInfo? TransformHandler(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        var info = new HandlerInfo
        {
            HandlerTypeFqn = ToFullyQualified(typeSymbol),
            HandlerDisplayName = typeSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            Location = typeSymbol.Locations.FirstOrDefault() ?? Location.None
        };

        var cancellationTokenType = context.SemanticModel.Compilation.GetTypeByMetadataName("System.Threading.CancellationToken");

        foreach (var member in typeSymbol.GetMembers().OfType<IMethodSymbol>())
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (member.MethodKind != MethodKind.Ordinary ||
                member.IsStatic ||
                member.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            if (member.Name == "Handle")
            {
                TryAddSyncMethod(info, member);
                continue;
            }

            if (member.Name == "HandleAsync")
            {
                TryAddAsyncMethod(info, member, cancellationTokenType);
            }
        }

        return info;
    }

    private static void TryAddSyncMethod(HandlerInfo handler, IMethodSymbol method)
    {
        if (method.Parameters.Length != 1 || IsTaskLike(method.ReturnType))
        {
            return;
        }

        handler.Methods.Add(new DispatchMethodInfo
        {
            CommandTypeFqn = ToFullyQualified(method.Parameters[0].Type),
            CommandDisplayName = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            HandlerTypeFqn = handler.HandlerTypeFqn,
            HandlerDisplayName = handler.HandlerDisplayName,
            ReturnTypeFqn = method.ReturnsVoid ? "void" : ToFullyQualified(method.ReturnType),
            MethodName = "Handle",
            IsAsync = false,
            HasCancellationTokenParameter = false,
            Location = method.Locations.FirstOrDefault() ?? handler.Location
        });
    }

    private static void TryAddAsyncMethod(
        HandlerInfo handler,
        IMethodSymbol method,
        INamedTypeSymbol? cancellationTokenType)
    {
        if (method.Parameters.Length is < 1 or > 2)
        {
            return;
        }

        if (!IsTaskLike(method.ReturnType))
        {
            return;
        }

        if (method.Parameters.Length == 2 &&
            (cancellationTokenType is null ||
             !SymbolEqualityComparer.Default.Equals(method.Parameters[1].Type, cancellationTokenType)))
        {
            return;
        }

        handler.Methods.Add(new DispatchMethodInfo
        {
            CommandTypeFqn = ToFullyQualified(method.Parameters[0].Type),
            CommandDisplayName = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            HandlerTypeFqn = handler.HandlerTypeFqn,
            HandlerDisplayName = handler.HandlerDisplayName,
            ReturnTypeFqn = ToFullyQualified(method.ReturnType),
            MethodName = "HandleAsync",
            IsAsync = true,
            HasCancellationTokenParameter = method.Parameters.Length == 2,
            Location = method.Locations.FirstOrDefault() ?? handler.Location
        });
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<HandlerInfo> handlers)
    {
        if (handlers.IsDefaultOrEmpty)
        {
            return;
        }

        var registrations = new SortedSet<string>(StringComparer.Ordinal);
        var methods = new List<DispatchMethodInfo>();

        foreach (var handler in handlers)
        {
            registrations.Add(handler.HandlerTypeFqn);

            if (handler.Methods.Count == 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    AD001,
                    handler.Location,
                    handler.HandlerDisplayName));
                continue;
            }

            foreach (var method in handler.Methods)
            {
                methods.Add(method);

                if (method.IsAsync && !method.HasCancellationTokenParameter)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        AD003,
                        method.Location,
                        method.HandlerDisplayName,
                        method.CommandDisplayName));
                }
            }
        }

        if (methods.Count == 0)
        {
            return;
        }

        var duplicateCommands = new HashSet<string>(StringComparer.Ordinal);
        foreach (var group in methods.GroupBy(static method => method.CommandTypeFqn, StringComparer.Ordinal))
        {
            if (group.Count() <= 1)
            {
                continue;
            }

            duplicateCommands.Add(group.Key);
            var ordered = group
                .OrderBy(static method => method.HandlerTypeFqn, StringComparer.Ordinal)
                .ThenBy(static method => method.MethodName, StringComparer.Ordinal)
                .ToArray();

            var first = ordered[0];
            for (var i = 1; i < ordered.Length; i++)
            {
                var duplicate = ordered[i];
                context.ReportDiagnostic(Diagnostic.Create(
                    AD002,
                    duplicate.Location,
                    duplicate.CommandDisplayName,
                    first.HandlerDisplayName,
                    duplicate.HandlerDisplayName));
            }
        }

        var dispatchMethods = methods
            .Where(method => !duplicateCommands.Contains(method.CommandTypeFqn))
            .OrderBy(static method => method.CommandTypeFqn, StringComparer.Ordinal)
            .ThenBy(static method => method.HandlerTypeFqn, StringComparer.Ordinal)
            .ToArray();

        if (dispatchMethods.Length == 0)
        {
            return;
        }

        context.AddSource("AutoDispatch.Dispatcher.g.cs", GenerateDispatcherSource(dispatchMethods));
        context.AddSource("AutoDispatch.Registration.g.cs", GenerateRegistrationSource(registrations));
    }

    private static string GenerateDispatcherSource(IReadOnlyList<DispatchMethodInfo> methods)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoDispatch.Generator/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoDispatch");
        sb.AppendLine("{");
        sb.AppendLine("    public interface IDispatcher");
        sb.AppendLine("    {");

        foreach (var method in methods)
        {
            sb.Append("        ");
            sb.Append(GetInterfaceReturnType(method));
            sb.Append(' ');
            sb.Append(GetDispatchMethodName(method));
            sb.Append('(');
            sb.Append(method.CommandTypeFqn);
            sb.Append(" command");
            if (method.IsAsync)
            {
                sb.Append(", global::System.Threading.CancellationToken ct = default");
            }

            sb.AppendLine(");");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal sealed class Dispatcher : IDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.IServiceProvider _sp;");
        sb.AppendLine();
        sb.AppendLine("        public Dispatcher(global::System.IServiceProvider sp) => _sp = sp;");
        sb.AppendLine();

        foreach (var method in methods)
        {
            sb.Append("        public ");
            sb.Append(GetInterfaceReturnType(method));
            sb.Append(' ');
            sb.Append(GetDispatchMethodName(method));
            sb.Append('(');
            sb.Append(method.CommandTypeFqn);
            sb.Append(" command");
            if (method.IsAsync)
            {
                sb.Append(", global::System.Threading.CancellationToken ct = default");
            }

            sb.AppendLine(")");
            sb.Append("            => this._sp.GetRequiredService<");
            sb.Append(method.HandlerTypeFqn);
            sb.Append(">().");
            sb.Append(method.MethodName);
            sb.Append("(command");
            if (method.IsAsync && method.HasCancellationTokenParameter)
            {
                sb.Append(", ct");
            }

            sb.AppendLine(");");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateRegistrationSource(IEnumerable<string> handlerTypeNames)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoDispatch.Generator/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoDispatch");
        sb.AppendLine("{");
        sb.AppendLine("    public static class AutoDispatchServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoDispatch(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var handlerTypeName in handlerTypeNames)
        {
            sb.Append("            services.AddScoped<");
            sb.Append(handlerTypeName);
            sb.AppendLine(">();");
        }

        sb.AppendLine("            services.AddScoped<global::AutoDispatch.IDispatcher, global::AutoDispatch.Dispatcher>();");
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool IsTaskLike(ITypeSymbol returnType)
    {
        if (returnType is not INamedTypeSymbol namedType)
        {
            return false;
        }

        var constructedFrom = namedType.ConstructedFrom.ToDisplayString();
        return namedType.ToDisplayString() == "System.Threading.Tasks.Task" ||
               constructedFrom == "System.Threading.Tasks.Task<TResult>";
    }

    private static string ToFullyQualified(ITypeSymbol typeSymbol) =>
        typeSymbol.ToDisplayString(FullyQualifiedFormat);

    private static string GetDispatchMethodName(DispatchMethodInfo method) =>
        method.IsAsync ? "SendAsync" : "Send";

    private static string GetInterfaceReturnType(DispatchMethodInfo method) =>
        method.ReturnTypeFqn;

    private sealed class HandlerInfo
    {
        public string HandlerTypeFqn { get; set; } = string.Empty;

        public string HandlerDisplayName { get; set; } = string.Empty;

        public Location Location { get; set; } = Location.None;

        public List<DispatchMethodInfo> Methods { get; } = new();
    }

    private sealed class DispatchMethodInfo
    {
        public string CommandTypeFqn { get; set; } = string.Empty;

        public string CommandDisplayName { get; set; } = string.Empty;

        public string HandlerTypeFqn { get; set; } = string.Empty;

        public string HandlerDisplayName { get; set; } = string.Empty;

        public string ReturnTypeFqn { get; set; } = string.Empty;

        public string MethodName { get; set; } = string.Empty;

        public bool IsAsync { get; set; }

        public bool HasCancellationTokenParameter { get; set; }

        public Location Location { get; set; } = Location.None;
    }
}
