using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace AutoDispatch;

[Generator]
public sealed class AutoDispatchGenerator : IIncrementalGenerator
{
    private const string AttributeSource = @"// <auto-generated by AutoDispatch.Generator/>
#nullable enable
using System;

namespace AutoDispatch
{
    /// <summary>Controls the DI lifetime used when registering a handler via AddAutoDispatch().</summary>
    public enum HandlerLifetime
    {
        /// <summary>Register as a scoped service (default).</summary>
        Scoped = 0,
        /// <summary>Register as a singleton service.</summary>
        Singleton = 1,
        /// <summary>Register as a transient service.</summary>
        Transient = 2
    }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class HandlerAttribute : Attribute
    {
        /// <summary>The DI lifetime for this handler. Defaults to Scoped.</summary>
        public HandlerLifetime Lifetime { get; set; } = HandlerLifetime.Scoped;
    }

    /// <summary>
    /// Semantic alias for <see cref=""HandlerAttribute""/> — use on command handlers to make
    /// intent explicit. Behaves identically to <c>[Handler]</c>.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class CommandHandlerAttribute : Attribute
    {
        /// <summary>The DI lifetime for this handler. Defaults to Scoped.</summary>
        public HandlerLifetime Lifetime { get; set; } = HandlerLifetime.Scoped;
    }

    /// <summary>
    /// Semantic alias for <see cref=""HandlerAttribute""/> — use on query handlers to make
    /// intent explicit. Behaves identically to <c>[Handler]</c>.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class QueryHandlerAttribute : Attribute
    {
        /// <summary>The DI lifetime for this handler. Defaults to Scoped.</summary>
        public HandlerLifetime Lifetime { get; set; } = HandlerLifetime.Scoped;
    }

    public readonly struct Unit { public static readonly Unit Value = default; }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class BehaviorAttribute : Attribute
    {
        public int Order { get; set; } = 0;
    }

    public interface IPipelineBehavior<TCommand, TResult>
    {
        System.Threading.Tasks.Task<TResult> HandleAsync(
            TCommand command,
            System.Func<System.Threading.Tasks.Task<TResult>> next,
            System.Threading.CancellationToken ct = default);
    }
}
";

    private static readonly DiagnosticDescriptor AD001 = new(
        id: "AD001",
        title: "Handler has no dispatch methods",
        messageFormat: "[Handler] on '{0}' has no `Handle` or `HandleAsync` methods. No dispatch methods will be generated.",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AD002 = new(
        id: "AD002",
        title: "Duplicate handler for command",
        messageFormat: "Duplicate handler for command '{0}': both '{1}' and '{2}' define a `Handle`/`HandleAsync` method for this command type. Remove one handler or rename the method.",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AD003 = new(
        id: "AD003",
        title: "HandleAsync missing CancellationToken",
        messageFormat: "`HandleAsync` on '{0}' for command '{1}' is missing a `CancellationToken` parameter. Consider adding `CancellationToken ct = default` as the second parameter.",
        category: "AutoDispatch",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly SymbolDisplayFormat FullyQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("AutoDispatch.Attributes.g.cs", AttributeSource));

        var handlers = MakeHandlerProvider(context, "AutoDispatch.HandlerAttribute")
            .Collect()
            .Combine(MakeHandlerProvider(context, "AutoDispatch.CommandHandlerAttribute").Collect())
            .Combine(MakeHandlerProvider(context, "AutoDispatch.QueryHandlerAttribute").Collect());

        var behaviors = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoDispatch.BehaviorAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => TransformBehavior(ctx, ct))
            .Where(static b => b is not null)
            .Select(static (b, _) => b!)
            .Collect();

        var allInputs = handlers.Combine(behaviors);

        context.RegisterSourceOutput(allInputs, static (ctx, tuple) =>
        {
            var (handlersTuple, behaviorList) = tuple;
            var ((h1, h2), h3) = handlersTuple;
            Generate(ctx, h1.AddRange(h2).AddRange(h3), behaviorList);
        });
    }

    private static IncrementalValuesProvider<HandlerInfo> MakeHandlerProvider(
        IncrementalGeneratorInitializationContext context,
        string attributeFqn) =>
        context.SyntaxProvider
            .ForAttributeWithMetadataName(
                attributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => TransformHandler(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

    private static HandlerInfo? TransformHandler(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        var info = new HandlerInfo
        {
            HandlerTypeFqn = ToFullyQualified(typeSymbol),
            HandlerDisplayName = typeSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            Location = typeSymbol.Locations.FirstOrDefault() ?? Location.None,
            LifetimeMethod = ReadLifetimeMethod(context.Attributes)
        };

        var cancellationTokenType = context.SemanticModel.Compilation.GetTypeByMetadataName("System.Threading.CancellationToken");

        foreach (var member in typeSymbol.GetMembers().OfType<IMethodSymbol>())
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (member.MethodKind != MethodKind.Ordinary ||
                member.IsStatic ||
                member.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            if (member.Name == "Handle")
            {
                TryAddSyncMethod(info, member);
                continue;
            }

            if (member.Name == "HandleAsync")
            {
                TryAddAsyncMethod(info, member, cancellationTokenType);
            }
        }

        return info;
    }

    private static void TryAddSyncMethod(HandlerInfo handler, IMethodSymbol method)
    {
        if (method.Parameters.Length != 1 || IsTaskLike(method.ReturnType))
        {
            return;
        }

        handler.Methods.Add(new DispatchMethodInfo
        {
            CommandTypeFqn = ToFullyQualified(method.Parameters[0].Type),
            CommandDisplayName = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            HandlerTypeFqn = handler.HandlerTypeFqn,
            HandlerDisplayName = handler.HandlerDisplayName,
            ReturnTypeFqn = method.ReturnsVoid ? "void" : ToFullyQualified(method.ReturnType),
            MethodName = "Handle",
            IsAsync = false,
            HasCancellationTokenParameter = false,
            Location = method.Locations.FirstOrDefault() ?? handler.Location
        });
    }

    private static void TryAddAsyncMethod(
        HandlerInfo handler,
        IMethodSymbol method,
        INamedTypeSymbol? cancellationTokenType)
    {
        if (method.Parameters.Length is < 1 or > 2)
        {
            return;
        }

        if (!IsTaskLike(method.ReturnType))
        {
            return;
        }

        if (method.Parameters.Length == 2 &&
            (cancellationTokenType is null ||
             !SymbolEqualityComparer.Default.Equals(method.Parameters[1].Type, cancellationTokenType)))
        {
            return;
        }

        handler.Methods.Add(new DispatchMethodInfo
        {
            CommandTypeFqn = ToFullyQualified(method.Parameters[0].Type),
            CommandDisplayName = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            HandlerTypeFqn = handler.HandlerTypeFqn,
            HandlerDisplayName = handler.HandlerDisplayName,
            ReturnTypeFqn = ToFullyQualified(method.ReturnType),
            MethodName = "HandleAsync",
            IsAsync = true,
            HasCancellationTokenParameter = method.Parameters.Length == 2,
            AsyncResultTypeFqn = GetAsyncResultTypeFqn(method.ReturnType),
            Location = method.Locations.FirstOrDefault() ?? handler.Location
        });
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<HandlerInfo> handlers, ImmutableArray<BehaviorInfo> behaviors)
    {
        if (handlers.IsDefaultOrEmpty)
        {
            return;
        }

        var registrations = new Dictionary<string, string>(StringComparer.Ordinal); // fqn → lifetime method
        var methods = new List<DispatchMethodInfo>();

        foreach (var handler in handlers)
        {
            registrations[handler.HandlerTypeFqn] = handler.LifetimeMethod;

            if (handler.Methods.Count == 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    AD001,
                    handler.Location,
                    handler.HandlerDisplayName));
                continue;
            }

            foreach (var method in handler.Methods)
            {
                methods.Add(method);

                if (method.IsAsync && !method.HasCancellationTokenParameter)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        AD003,
                        method.Location,
                        method.HandlerDisplayName,
                        method.CommandDisplayName));
                }
            }
        }

        if (methods.Count == 0)
        {
            return;
        }

        var duplicateCommands = new HashSet<string>(StringComparer.Ordinal);
        foreach (var group in methods.GroupBy(static method => method.CommandTypeFqn, StringComparer.Ordinal))
        {
            if (group.Count() <= 1)
            {
                continue;
            }

            duplicateCommands.Add(group.Key);
            var ordered = group
                .OrderBy(static method => method.HandlerTypeFqn, StringComparer.Ordinal)
                .ThenBy(static method => method.MethodName, StringComparer.Ordinal)
                .ToArray();

            var first = ordered[0];
            for (var i = 1; i < ordered.Length; i++)
            {
                var duplicate = ordered[i];
                context.ReportDiagnostic(Diagnostic.Create(
                    AD002,
                    duplicate.Location,
                    duplicate.CommandDisplayName,
                    first.HandlerDisplayName,
                    duplicate.HandlerDisplayName));
            }
        }

        var dispatchMethods = methods
            .Where(method => !duplicateCommands.Contains(method.CommandTypeFqn))
            .OrderBy(static method => method.CommandTypeFqn, StringComparer.Ordinal)
            .ThenBy(static method => method.HandlerTypeFqn, StringComparer.Ordinal)
            .ToArray();

        if (dispatchMethods.Length == 0)
        {
            return;
        }

        context.AddSource("AutoDispatch.Dispatcher.g.cs", GenerateDispatcherSource(dispatchMethods, behaviors));
        context.AddSource("AutoDispatch.Registration.g.cs", GenerateRegistrationSource(registrations, behaviors));
    }

    private static string GenerateDispatcherSource(IReadOnlyList<DispatchMethodInfo> methods, ImmutableArray<BehaviorInfo> behaviors)
    {
        var sortedBehaviors = behaviors.OrderBy(b => b.Order).ToArray();
        var hasBehaviors = sortedBehaviors.Length > 0;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoDispatch.Generator/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoDispatch");
        sb.AppendLine("{");
        sb.AppendLine("    public interface IDispatcher");
        sb.AppendLine("    {");

        foreach (var method in methods)
        {
            sb.Append("        ");
            sb.Append(GetInterfaceReturnType(method));
            sb.Append(' ');
            sb.Append(GetDispatchMethodName(method));
            sb.Append('(');
            sb.Append(method.CommandTypeFqn);
            sb.Append(" command");
            if (method.IsAsync)
            {
                sb.Append(", global::System.Threading.CancellationToken ct = default");
            }

            sb.AppendLine(");");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal sealed class Dispatcher : IDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.IServiceProvider _sp;");
        sb.AppendLine();
        sb.AppendLine("        public Dispatcher(global::System.IServiceProvider sp) => _sp = sp;");
        sb.AppendLine();

        foreach (var method in methods)
        {
            if (!method.IsAsync || !hasBehaviors)
            {
                // Simple expression-body form (sync or async with no behaviors)
                sb.Append("        public ");
                sb.Append(GetInterfaceReturnType(method));
                sb.Append(' ');
                sb.Append(GetDispatchMethodName(method));
                sb.Append('(');
                sb.Append(method.CommandTypeFqn);
                sb.Append(" command");
                if (method.IsAsync)
                {
                    sb.Append(", global::System.Threading.CancellationToken ct = default");
                }

                sb.AppendLine(")");
                sb.Append("            => this._sp.GetRequiredService<");
                sb.Append(method.HandlerTypeFqn);
                sb.Append(">().");
                sb.Append(method.MethodName);
                sb.Append("(command");
                if (method.IsAsync && method.HasCancellationTokenParameter)
                {
                    sb.Append(", ct");
                }

                sb.AppendLine(");");
                sb.AppendLine();
            }
            else
            {
                // Async with pipeline
                var resultFqn = method.AsyncResultTypeFqn ?? "global::AutoDispatch.Unit";
                var pipelineType = $"global::System.Func<global::System.Threading.Tasks.Task<{resultFqn}>>";

                sb.AppendLine($"        public {GetInterfaceReturnType(method)} {GetDispatchMethodName(method)}({method.CommandTypeFqn} command, global::System.Threading.CancellationToken ct = default)");
                sb.AppendLine("        {");

                if (method.AsyncResultTypeFqn != null)
                {
                    sb.AppendLine($"            {pipelineType} pipeline = () => this._sp.GetRequiredService<{method.HandlerTypeFqn}>().{method.MethodName}(command{(method.HasCancellationTokenParameter ? ", ct" : "")});");
                }
                else
                {
                    sb.AppendLine($"            {pipelineType} pipeline = async () => {{ await this._sp.GetRequiredService<{method.HandlerTypeFqn}>().{method.MethodName}(command{(method.HasCancellationTokenParameter ? ", ct" : "")}); return global::AutoDispatch.Unit.Value; }};");
                }

                for (var i = sortedBehaviors.Length - 1; i >= 0; i--)
                {
                    var b = sortedBehaviors[i];
                    var behaviorTypeFqn = $"{b.BaseTypeFqn}<{method.CommandTypeFqn}, {resultFqn}>";
                    sb.AppendLine($"            var _b{i} = this._sp.GetRequiredService<{behaviorTypeFqn}>();");
                    sb.AppendLine($"            var _p{i} = pipeline;");
                    sb.AppendLine($"            pipeline = () => _b{i}.HandleAsync(command, _p{i}, ct);");
                }

                sb.AppendLine("            return pipeline();");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateRegistrationSource(Dictionary<string, string> registrations, ImmutableArray<BehaviorInfo> behaviors)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoDispatch.Generator/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoDispatch");
        sb.AppendLine("{");
        sb.AppendLine("    public static class AutoDispatchServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoDispatch(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var kvp in registrations.OrderBy(k => k.Key, StringComparer.Ordinal))
        {
            sb.Append("            services.");
            sb.Append(kvp.Value);
            sb.Append('<');
            sb.Append(kvp.Key);
            sb.AppendLine(">();");
        }

        foreach (var behavior in behaviors.OrderBy(b => b.BaseTypeFqn, StringComparer.Ordinal))
        {
            sb.AppendLine($"            services.AddScoped(typeof({behavior.BaseTypeFqn}<,>));");
        }

        sb.AppendLine("            services.AddScoped<global::AutoDispatch.IDispatcher, global::AutoDispatch.Dispatcher>();");
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ReadLifetimeMethod(ImmutableArray<AttributeData> attributes)
    {
        foreach (var attr in attributes)
        {
            foreach (var arg in attr.NamedArguments)
            {
                if (arg.Key == "Lifetime" && arg.Value.Value is int val)
                {
                    return val switch
                    {
                        1 => "AddSingleton",
                        2 => "AddTransient",
                        _ => "AddScoped"
                    };
                }
            }
        }
        return "AddScoped";
    }

    private static bool IsTaskLike(ITypeSymbol returnType)
    {
        if (returnType is not INamedTypeSymbol namedType)
        {
            return false;
        }

        var constructedFrom = namedType.ConstructedFrom.ToDisplayString();
        return namedType.ToDisplayString() == "System.Threading.Tasks.Task" ||
               constructedFrom == "System.Threading.Tasks.Task<TResult>";
    }

    private static string ToFullyQualified(ITypeSymbol typeSymbol) =>
        typeSymbol.ToDisplayString(FullyQualifiedFormat);

    private static string GetDispatchMethodName(DispatchMethodInfo method) =>
        method.IsAsync ? "SendAsync" : "Send";

    private static string GetInterfaceReturnType(DispatchMethodInfo method) =>
        method.ReturnTypeFqn;

    private static string? GetAsyncResultTypeFqn(ITypeSymbol returnType)
    {
        if (returnType is INamedTypeSymbol { TypeArguments.Length: 1 } named)
        {
            return ToFullyQualified(named.TypeArguments[0]);
        }

        return null;
    }

    private static BehaviorInfo? TransformBehavior(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        if (typeSymbol.TypeParameters.Length != 2)
        {
            return null;
        }

        var order = 0;
        foreach (var attr in context.Attributes)
        {
            foreach (var arg in attr.NamedArguments)
            {
                if (arg.Key == "Order" && arg.Value.Value is int v)
                {
                    order = v;
                }
            }
        }

        var ns = typeSymbol.ContainingNamespace?.IsGlobalNamespace == true
            ? ""
            : typeSymbol.ContainingNamespace?.ToDisplayString() + ".";

        return new BehaviorInfo
        {
            BaseTypeFqn = $"global::{ns}{typeSymbol.Name}",
            Order = order,
            Location = typeSymbol.Locations.FirstOrDefault() ?? Location.None
        };
    }

    private sealed class HandlerInfo
    {
        public string HandlerTypeFqn { get; set; } = string.Empty;

        public string HandlerDisplayName { get; set; } = string.Empty;

        public Location Location { get; set; } = Location.None;

        public string LifetimeMethod { get; set; } = "AddScoped";

        public List<DispatchMethodInfo> Methods { get; } = new();
    }

    private sealed class DispatchMethodInfo
    {
        public string CommandTypeFqn { get; set; } = string.Empty;

        public string CommandDisplayName { get; set; } = string.Empty;

        public string HandlerTypeFqn { get; set; } = string.Empty;

        public string HandlerDisplayName { get; set; } = string.Empty;

        public string ReturnTypeFqn { get; set; } = string.Empty;

        public string MethodName { get; set; } = string.Empty;

        public bool IsAsync { get; set; }

        public bool HasCancellationTokenParameter { get; set; }

        public string? AsyncResultTypeFqn { get; set; }

        public Location Location { get; set; } = Location.None;
    }

    private sealed class BehaviorInfo
    {
        public string BaseTypeFqn { get; set; } = string.Empty;

        public int Order { get; set; }

        public Location Location { get; set; } = Location.None;
    }
}
